tail=logを追跡
tail.cmd=tail -f -n 100
tail.args=logFilePath

cwlogtail=CloudWatch Logsを追跡
cwlogtail.cmd=/home/taira/tools/cwlogtail.sh
cwlogtail.args=logGroupName 分

sync_news=ニュース同期スクリプト
sync_news.cmd=/home/taira/tools/sync_kps_news.py

tailOpenweuiLog=OpenWebUIのログを追跡
tailOpenweuiLog.cmd=/home/taira/tools/tailOpenweuiLog.sh